### ISSUE TITLE
What is the origin of the signapk signature?

### ISSUE THREAD

**Issue by zenware** [xc0d3rz/metasploit-apk-embed-payload#1]
Is it just any old cert you created, and if so, why not include the openssl commands for certificate creation at script runtime? It seems like it makes sense for openssl to be a dependency of this project.

**Comment by 0vulns** [comment]
Hi,@zenware.
 The origin of the signapk signature is [Signapk](https://github.com/xc0d3rz/metasploit-apk-embed-payload/tree/master/embed_tools/signapk),you can replace those files [Certificate](https://github.com/xc0d3rz/metasploit-apk-embed-payload/blob/master/embed_tools/signapk/certificate.pem) and [key.pk8](https://github.com/xc0d3rz/metasploit-apk-embed-payload/blob/master/embed_tools/signapk/key.pk8) with your own.
