### ISSUE TITLE
backdoor priv esclate

### ISSUE THREAD

**Issue by ghost** [xc0d3rz/metasploit-apk-embed-payload#14]
i keep getting this error" stdapi_fs_ls" when i trying to look into the sdcard and cant even upload things but when us embed backdoor i can do anything i want is there anyway to fix it tks!

**Comment by 0vulns** [comment]
Hi @xinjie00 , Sorry to make you waiting for a long time.
I Believe there's some issues with application permission, I've tried it with WhatsApp and works well
See the permission after embedding unless same as original payload of metasploit permission, you've to set it manual

**Comment by 0vulns** [comment]
See [How to add manifest permission to android application](http://stackoverflow.com/questions/2169294/how-to-add-manifest-permission-to-android-application)

**Comment by ghost** [comment]
thank you for ur reply

2016-10-04 19:20 GMT+08:00 Mohammed Ali notifications@github.com:
