### ISSUE TITLE
Hooks not showing up.

### ISSUE THREAD

**Issue by agucova** [xc0d3rz/metasploit-apk-embed-payload#2]
<img width="440" alt="hook" src="https://cloud.githubusercontent.com/assets/4694408/16979233/f957f1a4-4e2d-11e6-802a-a991c383ae94.png">

I tried entering the path to the activity, but it's expecting a number... Any ideas?

**Comment by 0vulns** [comment]
Thanks @agucova.
#2 was fixed.
