### ISSUE TITLE
Unable to find correct hook automatically

### ISSUE THREAD

**Issue by aliz911** [xc0d3rz/metasploit-apk-embed-payload#5]
[!] Unable to find correct hook automatically.
[-] Error finding launcher activity. Exiting.
tried different apk`s same problem 
![apk](https://cloud.githubusercontent.com/assets/21064498/17708467/1bb9a2b6-63b3-11e6-9e93-98a67b797272.png)

**Comment by sparts** [comment]
my error :
[!] Unable to find correct hook automatically

**Comment by masonist13** [comment]
I too have this problem ........don't know why  is there a fix for that ?

**Comment by 0vulns** [comment]
Hi,
The tool is looking for smali files `LauncherActivity` to inject payload,  Some developers change or hide launcherActivity dir on extension So our tool cannot find it.

**Comment by 0vulns** [comment]
Fixed #18

**Comment by MustafaSoufi** [comment]
i can't solve this problem >> i want help plz ??????

**Comment by pbarnwal12** [comment]
i can't solve this problem >> i want help plz ??????
