### ISSUE TITLE
Don't Know What to do? Help Please

### ISSUE THREAD

**Issue by chandbing123** [xc0d3rz/metasploit-apk-embed-payload#9]
![screenshot from 2016-09-07 08-44-49](https://cloud.githubusercontent.com/assets/22052961/18312491/054babe2-74d8-11e6-939a-46ddd59affcc.png)
-Thanks for any help you can give me

**Comment by 0vulns** [comment]
``` bash
gem install bundler
 bundler install
```

**Comment by chandbing123** [comment]
![screenshot from 2016-09-07 09-48-56](https://cloud.githubusercontent.com/assets/22052961/18314275/613002b6-74e0-11e6-9122-de62a2a7ff68.png)
-Thanks again for your help

**Comment by chandbing123** [comment]
Now i am getting this message
![screenshot from 2016-09-07 10-01-22](https://cloud.githubusercontent.com/assets/22052961/18314699/238a59b4-74e2-11e6-91d5-c64511ba15f5.png)

**Comment by 0vulns** [comment]
See #8

**Comment by chandbing123** [comment]
Hey does this mean there is something wrong with the original apk file i downloaded or something else?
![screenshot from 2016-09-07 10-39-07](https://cloud.githubusercontent.com/assets/22052961/18316149/7fa6f0fe-74e7-11e6-8148-f6ed94b67895.png)
-Thanks this will be my last question
